#include <WinSock2.h>
#include <atomic>
#include <string>
#include <algorithm>
#include <functional>
#include "../MultiSocketRUDPClient/RUDPClientCore.h"
#include "../ContentsServer/Protocol.h"
#include "../Common/Crypto/CryptoHelper.h"
#include <format>
#ifndef LOG_ERROR
#define LOG_ERROR(...) ((void)0)
#endif
#include "../Common/PacketCrypto/PacketCryptoHelper.h"

// Client and server SendPacketInfo have distinct layouts, so client-only checks
// run in the client harness rather than linking both implementations into CoreTest.
class RUDPClientCoreTestAccess
{
	class CallbackPacket final : public IPacket
	{
	public:
		explicit CallbackPacket(std::function<void()> inCallback) : callback(std::move(inCallback)) {}
		PacketId GetPacketId() const override { return 77; }
		void PacketToBuffer(NetBuffer&) override { callback(); }
	private:
		std::function<void()> callback;
	};
public:
	static bool Run()
	{
		RUDPClientCore client;
		client.unreliableQueueCapacity = 3;
		client.isStopped = false;
		client.isConnected = true;
		client.sendEventHandles[0] = CreateSemaphore(nullptr, 0, LONG_MAX, nullptr);
		std::fill_n(client.sessionKey, SESSION_KEY_SIZE, 0);
		std::fill_n(client.sessionSalt, SESSION_SALT_SIZE, 0);
		auto& crypto = CryptoHelper::GetTLSInstance();
		client.keyObjectBuffer = new unsigned char[crypto.GetKeyObjectSize()];
		client.sessionKeyHandle = crypto.GetSymmetricKeyHandle(client.keyObjectBuffer, client.sessionKey);
		if (client.sessionKeyHandle == nullptr || client.sendEventHandles[0] == nullptr)
		{
			client.Stop();
			return false;
		}
		bool passed = true;
		TestStringPacketReq request;
		request.testString = "queue-test";
		for (int index = 0; index < 4; ++index)
		{
			passed &= client.SendUnreliablePacket(request);
		}
		passed &= client.unreliableSendQueue.size() == 3 && client.sendPacketInfoMap.empty() &&
			client.lastSendPacketSequence == 0 && client.pendingPacketQueue.empty();
		PacketSequence expected = 2;
		for (auto* buffer : client.unreliableSendQueue)
		{
			PacketSequence sequence{};
			memcpy(&sequence, buffer->GetReadBufferPtr() + df_HEADER_SIZE + sizeof(PACKET_TYPE), sizeof(sequence));
			passed &= sequence == expected++;
		}

		// A forged high sequence must not advance the authenticated receive state.
		Receive(client, 100, true);
		passed &= client.authenticatedReceiveCount.load() == 0;
		for (const PacketSequence sequence : { 0, 5, 3, 5, 7, 9 }) Receive(client, sequence, false);
		passed &= client.authenticatedReceiveCount.load() == 6;
		passed &= client.serverAliveChecker.IsServerAlive(client.authenticatedReceiveCount.load());
		Receive(client, 200, true);
		passed &= not client.serverAliveChecker.IsServerAlive(client.authenticatedReceiveCount.load());
		passed &= client.unreliableReceivedPackets.size() == 3 && client.nextRecvPacketSequence == 1 &&
			client.sendBufferQueue.GetRestSize() == 0;
		for (const PacketSequence sequence : { 5, 7, 9 })
		{
			auto* buffer = client.GetReceivedUnreliablePacket();
			if (buffer == nullptr) { passed = false; break; }
			PacketId packetId{};
			PacketSequence value{};
			*buffer >> packetId >> value;
			passed &= packetId == 77 && value == sequence;
			NetBuffer::Free(buffer);
		}
		Receive(client, 10, false);
		Receive(client, 1, false, PACKET_TYPE::HEARTBEAT_TYPE);
		Receive(client, 1, false, PACKET_TYPE::HEARTBEAT_TYPE);
		passed &= client.recvPacketHoldingQueue.empty() && client.nextRecvPacketSequence == 2;
		// A heartbeat behind a gap must wait; content remains available to the application.
		Receive(client, 3, false, PACKET_TYPE::HEARTBEAT_TYPE);
		passed &= client.nextRecvPacketSequence == 2 && client.recvPacketHoldingQueue.size() == 1;
		Receive(client, 2, false, PACKET_TYPE::SEND_TYPE);
		passed &= client.nextRecvPacketSequence == 2 && client.recvPacketHoldingQueue.size() == 2;
		auto* content = client.GetReceivedPacket();
		if (content != nullptr)
		{
			PacketId id{};
			PacketSequence value{};
			*content >> id >> value;
			passed &= id == 77 && value == 2;
			NetBuffer::Free(content);
		}
		else passed = false;
		passed &= client.recvPacketHoldingQueue.empty() && client.nextRecvPacketSequence == 4;
		Receive(client, 5, false, PACKET_TYPE::HEARTBEAT_TYPE);
		Receive(client, 6, false, PACKET_TYPE::SEND_TYPE);
		// This harness has no send worker; release the ACKs generated by the injected packets.
		NetBuffer* ack{};
		while (client.sendBufferQueue.Dequeue(&ack)) NetBuffer::Free(ack);
		client.Stop();
		passed &= client.recvPacketHoldingQueue.empty() && client.nextRecvPacketSequence == 1;
		passed &= client.unreliableSendQueue.empty() && client.unreliableReceivedPackets.empty() &&
			client.lastUnreliableSendSequence == 0 && client.unreliableReceiveState.Accept(1);
		passed &= not client.SendUnreliablePacket(request);
		// Model Stop + Start while an earlier call is still serializing user data.
		client.isStopped = false;
		client.threadStopFlag = false;
		client.isConnected = true;
		CallbackPacket pausedSerializer([&]()
		{
			client.Stop();
			client.isStopped = false;
			client.threadStopFlag = false;
			client.isConnected = true;
			client.sendEventHandles[0] = CreateSemaphore(nullptr, 0, LONG_MAX, nullptr);
		});
		passed &= not client.SendUnreliablePacket(pausedSerializer);
		passed &= client.lastUnreliableSendSequence == 0 && client.unreliableSendQueue.empty();
		client.Stop();
		return passed;
	}

private:
	static void Receive(RUDPClientCore& client, const PacketSequence sequence, const bool tampered,
		PACKET_TYPE type = PACKET_TYPE::UNRELIABLE_SEND_TYPE)
	{
		auto* buffer = NetBuffer::Alloc();
		const bool isCore = type == PACKET_TYPE::HEARTBEAT_TYPE;
		*buffer << type << sequence;
		if (not isCore) *buffer << PacketId{ 77 } << sequence;
		const auto direction = type == PACKET_TYPE::UNRELIABLE_SEND_TYPE ?
			PACKET_DIRECTION::SERVER_TO_CLIENT_UNREL : PACKET_DIRECTION::SERVER_TO_CLIENT;
		PacketCryptoHelper::EncodePacket(*buffer, sequence, direction,
			client.sessionSalt, SESSION_SALT_SIZE, client.sessionKeyHandle, isCore);
		if (tampered) buffer->GetReadBufferPtr()[buffer->GetUseSize() - 1] ^= 1;
		char header[df_HEADER_SIZE];
		buffer->ReadBuffer(header, sizeof(header));
		client.ProcessRecvPacket(*buffer);
		NetBuffer::Free(buffer);
	}
};

bool RunUnreliableClientChecks()
{
	return RUDPClientCoreTestAccess::Run();
}
