// <auto-generated />
using MultiSocketRUDPBotTester.Bot;
using Xunit;

namespace MultiSocketRUDPBotTester.UnitTests;

public class GeneratedPacketPayloadTests
{
    [Fact]
    public void PingMatchesWirePayload()
    {
        Assert.Equal(1u, (uint)PacketId.Ping);
        var node = new SendPacketNode
        {
            PacketId = PacketId.Ping,
            FieldValues = new()
            {
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString(""), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
    [Fact]
    public void PongMatchesWirePayload()
    {
        Assert.Equal(2u, (uint)PacketId.Pong);
        var node = new SendPacketNode
        {
            PacketId = PacketId.Pong,
            FieldValues = new()
            {
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString(""), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
    [Fact]
    public void TestStringPacketReqMatchesWirePayload()
    {
        Assert.Equal(3u, (uint)PacketId.TestStringPacketReq);
        var node = new SendPacketNode
        {
            PacketId = PacketId.TestStringPacketReq,
            FieldValues = new()
            {
                ["testString"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("\"packet-\\ud55c\\uae00-0\""),
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString("0f007061636b65742ded959ceab8802d30"), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
    [Fact]
    public void TestStringPacketResMatchesWirePayload()
    {
        Assert.Equal(4u, (uint)PacketId.TestStringPacketRes);
        var node = new SendPacketNode
        {
            PacketId = PacketId.TestStringPacketRes,
            FieldValues = new()
            {
                ["echoString"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("\"packet-\\ud55c\\uae00-0\""),
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString("0f007061636b65742ded959ceab8802d30"), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
    [Fact]
    public void TestPacketReqMatchesWirePayload()
    {
        Assert.Equal(5u, (uint)PacketId.TestPacketReq);
        var node = new SendPacketNode
        {
            PacketId = PacketId.TestPacketReq,
            FieldValues = new()
            {
                ["order"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("-1234567"),
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString("7929edff"), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
    [Fact]
    public void TestPacketResMatchesWirePayload()
    {
        Assert.Equal(6u, (uint)PacketId.TestPacketRes);
        var node = new SendPacketNode
        {
            PacketId = PacketId.TestPacketRes,
            FieldValues = new()
            {
                ["order"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("-1234567"),
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString("7929edff"), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
    [Fact]
    public void ChannelEchoReqMatchesWirePayload()
    {
        Assert.Equal(7u, (uint)PacketId.ChannelEchoReq);
        var node = new SendPacketNode
        {
            PacketId = PacketId.ChannelEchoReq,
            FieldValues = new()
            {
                ["requestId"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("81985529216486895"),
                ["unreliable"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("174"),
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString("efcdab8967452301ae"), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
    [Fact]
    public void ChannelEchoResMatchesWirePayload()
    {
        Assert.Equal(8u, (uint)PacketId.ChannelEchoRes);
        var node = new SendPacketNode
        {
            PacketId = PacketId.ChannelEchoRes,
            FieldValues = new()
            {
                ["requestId"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("81985529216486895"),
                ["unreliable"] = System.Text.Json.JsonSerializer.Deserialize<System.Text.Json.JsonElement>("174"),
            }
        };
        var buffer = node.BuildFromSchema();
        Assert.NotNull(buffer);
        Assert.Equal(Convert.FromHexString("efcdab8967452301ae"), buffer.GetPacketBuffer().AsSpan(5).ToArray());
    }
}
