#pragma once

#define NO_USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME 0
#define USE_WORKER_THREAD_SLEEP_FOR_FRAME 1
#define USE_WORKER_THREAD_SLEEP_ZERO 2

#if defined(RUDP_RTT_BENCHMARK_BUILD)
#define USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME NO_USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME
#elif !defined(USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME)
#define USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME USE_WORKER_THREAD_SLEEP_ZERO
#endif

#if defined(RUDP_RTT_BENCHMARK_BUILD) && \
	USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME != NO_USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME
#error RTT benchmark must disable IO worker thread sleep
#endif

#if USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME < NO_USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME || \
	USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME > USE_WORKER_THREAD_SLEEP_ZERO
#error Invalid USE_IO_WORKER_THREAD_SLEEP_FOR_FRAME value
#endif
