#pragma once
#include <cstdint>

enum class RIO_OPERATION_TYPE : char
{
	OP_ERROR = 0
	, OP_RECV
	, OP_SEND
};

enum class PACKET_TYPE : unsigned char
{
	INVALID_TYPE = 0
	, CONNECT_TYPE
	, DISCONNECT_TYPE
	, SEND_TYPE
	, SEND_REPLY_TYPE
	, HEARTBEAT_TYPE
	, HEARTBEAT_REPLY_TYPE
};

enum class CONNECT_RESULT_CODE : unsigned char
{
	SUCCESS = 0
	, SERVER_FULL
	, ALREADY_CONNECTED_SESSION
	, CREATE_SOCKET_FAILED
	, RIO_INIT_FAILED
	, DO_RECV_FAILED
	, SESSION_KEY_GENERATION_FAILED
};

enum class PACKET_DIRECTION : uint8_t
{
	CLIENT_TO_SERVER = 0,
	CLIENT_TO_SERVER_REPLY = 1,
	SERVER_TO_CLIENT = 2,
	SERVER_TO_CLIENT_REPLY = 3,
	INVALID = 255
};

enum class SESSION_STATE : uint8_t
{
	DISCONNECTED = 0,
	RESERVED = 1,
	CONNECTED = 2,
	RELEASING = 3
};

enum class THREAD_GROUP : uint8_t
{
	IO_WORKER_THREAD = 0,
	RECV_LOGIC_WORKER_THREAD = 1,
	RETRANSMISSION_THREAD = 2,
	SESSION_RELEASE_THREAD = 3,
	HEARTBEAT_THREAD = 4,
};